[build]
builder = "nixpacks"

[[services]]
name = "backend"
source = "apps/backend"
startCommand = "npx prisma migrate deploy && node dist/index.js"

[services.envs]
PORT = "4000"

[[services]]
name = "frontend"
source = "apps/frontend"
startCommand = "node .next/standalone/server.js"

[services.envs]
PORT = "3000"
